//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch_Tbl
    {
        public int branchid { get; set; }
        public string branch_name { get; set; }
        public string ifsc_code { get; set; }
        public string location { get; set; }
        public string city { get; set; }
    }
}
