//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan_Tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loan_Tbl()
        {
            this.Loandetail_Tbl = new HashSet<Loandetail_Tbl>();
        }
    
        public int loanid { get; set; }
        public string type { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<double> interest { get; set; }
        public Nullable<int> duration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loandetail_Tbl> Loandetail_Tbl { get; set; }
    }
}
