//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BankingSystem_DBEntities : DbContext
    {
        public BankingSystem_DBEntities()
            : base("name=BankingSystem_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_Tbl> Admin_Tbl { get; set; }
        public virtual DbSet<Branch_Tbl> Branch_Tbl { get; set; }
        public virtual DbSet<Customer_Tbl> Customer_Tbl { get; set; }
        public virtual DbSet<Loan_Tbl> Loan_Tbl { get; set; }
        public virtual DbSet<Loandetail_Tbl> Loandetail_Tbl { get; set; }
        public virtual DbSet<Transaction_Tbl> Transaction_Tbl { get; set; }
    }
}
